export const taskListActionTypes = {
  TASK_LISTS_REQUEST: 'TASK_LISTS_REQUEST',
  TASK_LISTS_SUCCESS: 'TASK_LISTS_SUCCESS',
  TASK_LISTS_ERROR: 'TASK_LISTS_ERROR',

  UPDATE_TASK_LIST_REQUEST: 'UPDATE_TASK_LIST_REQUEST',
  UPDATE_TASK_LIST_SUCCESS: 'UPDATE_TASK_LIST_SUCCESS',
  UPDATE_TASK_LIST_ERROR: 'UPDATE_TASK_LIST_ERROR',

  DELETE_TASK_LIST_REQUEST: 'DELETE_TASK_LIST_REQUEST',
  DELETE_TASK_LIST_SUCCESS: 'DELETE_TASK_LIST_SUCCESS',
  DELETE_TASK_LIST_ERROR: 'DELETE_TASK_LIST_ERROR',
  CLEAR_DELETED_STATE: 'CLEAR_DELETED_STATE',
};
