export const authActionTypes = {
  SIGN_IN_USER: 'SIGN_IN_USER',
  SIGN_IN_FAIL: 'SIGN_IN_FAIL',
  SUCCESSFUL_SIGN_IN: 'SUCCESSFUL_SIGN_IN',
  LOGGED_OUT: 'LOGGED_OUT',
  SIGN_UP_USER: 'SIGN_UP_USER',
  SUCCESSFUL_SIGN_UP: 'SUCCESSFUL_SIGN_UP',
  SIGN_UP_FAIL: 'SIGN_UP_FAIL',
  SET_ERROR_MESSAGE: 'SET_ERROR_MESSAGE',
  CLEAR_ERROR_MESSAGE: 'CLEAR_ERROR_MESSAGE',
};
