export const userActionTypes = {
  LOGIN_USER: 'LOGIN_USER',
  SIGN_IN_FAIL: 'SIGN_IN_FAIL',
  SUCCESSFUL_LOGIN: 'SUCCESSFUL_LOGIN',
  LOGGED_OUT: 'LOGGED_OUT',
  SIGN_UP_USER: 'SIGN_UP_USER',
  SUCCESSFUL_SIGN_UP: 'SUCCESSFUL_SIGN_UP',
  SIGN_UP_FAIL: 'SIGN_UP_FAIL',
};
